/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPushTestRouteImport } from './routes/_authenticated/push-test'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedReferralsNewRouteImport } from './routes/_authenticated/referrals.new'
import { Route as AuthenticatedReferralsIdRouteImport } from './routes/_authenticated/referrals.$id'
import { Route as AuthenticatedInboxIdRouteImport } from './routes/_authenticated/inbox.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPushTestRoute = AuthenticatedPushTestRouteImport.update({
  id: '/push-test',
  path: '/push-test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsNewRoute =
  AuthenticatedReferralsNewRouteImport.update({
    id: '/referrals/new',
    path: '/referrals/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferralsIdRoute =
  AuthenticatedReferralsIdRouteImport.update({
    id: '/referrals/$id',
    path: '/referrals/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxIdRoute = AuthenticatedInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedInboxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/push-test': typeof AuthenticatedPushTestRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/referrals/$id': typeof AuthenticatedReferralsIdRoute
  '/referrals/new': typeof AuthenticatedReferralsNewRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/push-test': typeof AuthenticatedPushTestRoute
  '/': typeof AuthenticatedIndexRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/referrals/$id': typeof AuthenticatedReferralsIdRoute
  '/referrals/new': typeof AuthenticatedReferralsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/push-test': typeof AuthenticatedPushTestRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/_authenticated/referrals/$id': typeof AuthenticatedReferralsIdRoute
  '/_authenticated/referrals/new': typeof AuthenticatedReferralsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/admin'
    | '/analytics'
    | '/inbox'
    | '/notifications'
    | '/push-test'
    | '/inbox/$id'
    | '/referrals/$id'
    | '/referrals/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/admin'
    | '/analytics'
    | '/inbox'
    | '/notifications'
    | '/push-test'
    | '/'
    | '/inbox/$id'
    | '/referrals/$id'
    | '/referrals/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/inbox'
    | '/_authenticated/notifications'
    | '/_authenticated/push-test'
    | '/_authenticated/'
    | '/_authenticated/inbox/$id'
    | '/_authenticated/referrals/$id'
    | '/_authenticated/referrals/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/push-test': {
      id: '/_authenticated/push-test'
      path: '/push-test'
      fullPath: '/push-test'
      preLoaderRoute: typeof AuthenticatedPushTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals/new': {
      id: '/_authenticated/referrals/new'
      path: '/referrals/new'
      fullPath: '/referrals/new'
      preLoaderRoute: typeof AuthenticatedReferralsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals/$id': {
      id: '/_authenticated/referrals/$id'
      path: '/referrals/$id'
      fullPath: '/referrals/$id'
      preLoaderRoute: typeof AuthenticatedReferralsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/$id': {
      id: '/_authenticated/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AuthenticatedInboxIdRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
  }
}

interface AuthenticatedInboxRouteChildren {
  AuthenticatedInboxIdRoute: typeof AuthenticatedInboxIdRoute
}

const AuthenticatedInboxRouteChildren: AuthenticatedInboxRouteChildren = {
  AuthenticatedInboxIdRoute: AuthenticatedInboxIdRoute,
}

const AuthenticatedInboxRouteWithChildren =
  AuthenticatedInboxRoute._addFileChildren(AuthenticatedInboxRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPushTestRoute: typeof AuthenticatedPushTestRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedReferralsIdRoute: typeof AuthenticatedReferralsIdRoute
  AuthenticatedReferralsNewRoute: typeof AuthenticatedReferralsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPushTestRoute: AuthenticatedPushTestRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedReferralsIdRoute: AuthenticatedReferralsIdRoute,
  AuthenticatedReferralsNewRoute: AuthenticatedReferralsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
