/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ClinicalSafetyRouteImport } from './routes/clinical-safety'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPushTestRouteImport } from './routes/_authenticated/push-test'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedNotificationsAuditRouteImport } from './routes/_authenticated/notifications-audit'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedBoardRouteImport } from './routes/_authenticated/board'
import { Route as AuthenticatedBedBoardRouteImport } from './routes/_authenticated/bed-board'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPostopBookingsIndexRouteImport } from './routes/_authenticated/postop-bookings.index'
import { Route as AuthenticatedReferralsNewRouteImport } from './routes/_authenticated/referrals.new'
import { Route as AuthenticatedReferralsIdRouteImport } from './routes/_authenticated/referrals.$id'
import { Route as AuthenticatedPostopBookingsPlannerRouteImport } from './routes/_authenticated/postop-bookings.planner'
import { Route as AuthenticatedPostopBookingsNewRouteImport } from './routes/_authenticated/postop-bookings.new'
import { Route as AuthenticatedPostopBookingsCancellationsRouteImport } from './routes/_authenticated/postop-bookings.cancellations'
import { Route as AuthenticatedPostopBookingsAnalyticsRouteImport } from './routes/_authenticated/postop-bookings.analytics'
import { Route as AuthenticatedInboxIdRouteImport } from './routes/_authenticated/inbox.$id'
import { Route as AuthenticatedBoardWardRoundRouteImport } from './routes/_authenticated/board.ward-round'
import { Route as ApiPublicBridgeVerifySignatureRouteImport } from './routes/api/public/bridge/verify-signature'
import { Route as ApiPublicBridgeSyncRouteImport } from './routes/api/public/bridge/sync'
import { Route as ApiPublicBridgeReferralsRouteImport } from './routes/api/public/bridge/referrals'
import { Route as ApiPublicBridgePatientsRouteImport } from './routes/api/public/bridge/patients'
import { Route as ApiPublicBridgeNotificationsRouteImport } from './routes/api/public/bridge/notifications'
import { Route as ApiPublicBridgeMicrobiologyRouteImport } from './routes/api/public/bridge/microbiology'
import { Route as ApiPublicBridgeInvestigationsRouteImport } from './routes/api/public/bridge/investigations'
import { Route as ApiPublicBridgeHealthRouteImport } from './routes/api/public/bridge/health'
import { Route as ApiPublicBridgeAuditRouteImport } from './routes/api/public/bridge/audit'
import { Route as AuthenticatedPostopBookingsIdEditRouteImport } from './routes/_authenticated/postop-bookings.$id.edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalSafetyRoute = ClinicalSafetyRouteImport.update({
  id: '/clinical-safety',
  path: '/clinical-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPushTestRoute = AuthenticatedPushTestRouteImport.update({
  id: '/push-test',
  path: '/push-test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsAuditRoute =
  AuthenticatedNotificationsAuditRouteImport.update({
    id: '/notifications-audit',
    path: '/notifications-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardRoute = AuthenticatedBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBedBoardRoute = AuthenticatedBedBoardRouteImport.update({
  id: '/bed-board',
  path: '/bed-board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostopBookingsIndexRoute =
  AuthenticatedPostopBookingsIndexRouteImport.update({
    id: '/postop-bookings/',
    path: '/postop-bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferralsNewRoute =
  AuthenticatedReferralsNewRouteImport.update({
    id: '/referrals/new',
    path: '/referrals/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferralsIdRoute =
  AuthenticatedReferralsIdRouteImport.update({
    id: '/referrals/$id',
    path: '/referrals/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostopBookingsPlannerRoute =
  AuthenticatedPostopBookingsPlannerRouteImport.update({
    id: '/postop-bookings/planner',
    path: '/postop-bookings/planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostopBookingsNewRoute =
  AuthenticatedPostopBookingsNewRouteImport.update({
    id: '/postop-bookings/new',
    path: '/postop-bookings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostopBookingsCancellationsRoute =
  AuthenticatedPostopBookingsCancellationsRouteImport.update({
    id: '/postop-bookings/cancellations',
    path: '/postop-bookings/cancellations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostopBookingsAnalyticsRoute =
  AuthenticatedPostopBookingsAnalyticsRouteImport.update({
    id: '/postop-bookings/analytics',
    path: '/postop-bookings/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxIdRoute = AuthenticatedInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedInboxRoute,
} as any)
const AuthenticatedBoardWardRoundRoute =
  AuthenticatedBoardWardRoundRouteImport.update({
    id: '/ward-round',
    path: '/ward-round',
    getParentRoute: () => AuthenticatedBoardRoute,
  } as any)
const ApiPublicBridgeVerifySignatureRoute =
  ApiPublicBridgeVerifySignatureRouteImport.update({
    id: '/api/public/bridge/verify-signature',
    path: '/api/public/bridge/verify-signature',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeSyncRoute = ApiPublicBridgeSyncRouteImport.update({
  id: '/api/public/bridge/sync',
  path: '/api/public/bridge/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeReferralsRoute =
  ApiPublicBridgeReferralsRouteImport.update({
    id: '/api/public/bridge/referrals',
    path: '/api/public/bridge/referrals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgePatientsRoute = ApiPublicBridgePatientsRouteImport.update({
  id: '/api/public/bridge/patients',
  path: '/api/public/bridge/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeNotificationsRoute =
  ApiPublicBridgeNotificationsRouteImport.update({
    id: '/api/public/bridge/notifications',
    path: '/api/public/bridge/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeMicrobiologyRoute =
  ApiPublicBridgeMicrobiologyRouteImport.update({
    id: '/api/public/bridge/microbiology',
    path: '/api/public/bridge/microbiology',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeInvestigationsRoute =
  ApiPublicBridgeInvestigationsRouteImport.update({
    id: '/api/public/bridge/investigations',
    path: '/api/public/bridge/investigations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeHealthRoute = ApiPublicBridgeHealthRouteImport.update({
  id: '/api/public/bridge/health',
  path: '/api/public/bridge/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeAuditRoute = ApiPublicBridgeAuditRouteImport.update({
  id: '/api/public/bridge/audit',
  path: '/api/public/bridge/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostopBookingsIdEditRoute =
  AuthenticatedPostopBookingsIdEditRouteImport.update({
    id: '/postop-bookings/$id/edit',
    path: '/postop-bookings/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/clinical-safety': typeof ClinicalSafetyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bed-board': typeof AuthenticatedBedBoardRoute
  '/board': typeof AuthenticatedBoardRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/notifications-audit': typeof AuthenticatedNotificationsAuditRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/push-test': typeof AuthenticatedPushTestRoute
  '/board/ward-round': typeof AuthenticatedBoardWardRoundRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/postop-bookings/analytics': typeof AuthenticatedPostopBookingsAnalyticsRoute
  '/postop-bookings/cancellations': typeof AuthenticatedPostopBookingsCancellationsRoute
  '/postop-bookings/new': typeof AuthenticatedPostopBookingsNewRoute
  '/postop-bookings/planner': typeof AuthenticatedPostopBookingsPlannerRoute
  '/referrals/$id': typeof AuthenticatedReferralsIdRoute
  '/referrals/new': typeof AuthenticatedReferralsNewRoute
  '/postop-bookings/': typeof AuthenticatedPostopBookingsIndexRoute
  '/postop-bookings/$id/edit': typeof AuthenticatedPostopBookingsIdEditRoute
  '/api/public/bridge/audit': typeof ApiPublicBridgeAuditRoute
  '/api/public/bridge/health': typeof ApiPublicBridgeHealthRoute
  '/api/public/bridge/investigations': typeof ApiPublicBridgeInvestigationsRoute
  '/api/public/bridge/microbiology': typeof ApiPublicBridgeMicrobiologyRoute
  '/api/public/bridge/notifications': typeof ApiPublicBridgeNotificationsRoute
  '/api/public/bridge/patients': typeof ApiPublicBridgePatientsRoute
  '/api/public/bridge/referrals': typeof ApiPublicBridgeReferralsRoute
  '/api/public/bridge/sync': typeof ApiPublicBridgeSyncRoute
  '/api/public/bridge/verify-signature': typeof ApiPublicBridgeVerifySignatureRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/clinical-safety': typeof ClinicalSafetyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bed-board': typeof AuthenticatedBedBoardRoute
  '/board': typeof AuthenticatedBoardRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/notifications-audit': typeof AuthenticatedNotificationsAuditRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/push-test': typeof AuthenticatedPushTestRoute
  '/': typeof AuthenticatedIndexRoute
  '/board/ward-round': typeof AuthenticatedBoardWardRoundRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/postop-bookings/analytics': typeof AuthenticatedPostopBookingsAnalyticsRoute
  '/postop-bookings/cancellations': typeof AuthenticatedPostopBookingsCancellationsRoute
  '/postop-bookings/new': typeof AuthenticatedPostopBookingsNewRoute
  '/postop-bookings/planner': typeof AuthenticatedPostopBookingsPlannerRoute
  '/referrals/$id': typeof AuthenticatedReferralsIdRoute
  '/referrals/new': typeof AuthenticatedReferralsNewRoute
  '/postop-bookings': typeof AuthenticatedPostopBookingsIndexRoute
  '/postop-bookings/$id/edit': typeof AuthenticatedPostopBookingsIdEditRoute
  '/api/public/bridge/audit': typeof ApiPublicBridgeAuditRoute
  '/api/public/bridge/health': typeof ApiPublicBridgeHealthRoute
  '/api/public/bridge/investigations': typeof ApiPublicBridgeInvestigationsRoute
  '/api/public/bridge/microbiology': typeof ApiPublicBridgeMicrobiologyRoute
  '/api/public/bridge/notifications': typeof ApiPublicBridgeNotificationsRoute
  '/api/public/bridge/patients': typeof ApiPublicBridgePatientsRoute
  '/api/public/bridge/referrals': typeof ApiPublicBridgeReferralsRoute
  '/api/public/bridge/sync': typeof ApiPublicBridgeSyncRoute
  '/api/public/bridge/verify-signature': typeof ApiPublicBridgeVerifySignatureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/clinical-safety': typeof ClinicalSafetyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/setup': typeof SetupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bed-board': typeof AuthenticatedBedBoardRoute
  '/_authenticated/board': typeof AuthenticatedBoardRouteWithChildren
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/notifications-audit': typeof AuthenticatedNotificationsAuditRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/push-test': typeof AuthenticatedPushTestRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/board/ward-round': typeof AuthenticatedBoardWardRoundRoute
  '/_authenticated/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/_authenticated/postop-bookings/analytics': typeof AuthenticatedPostopBookingsAnalyticsRoute
  '/_authenticated/postop-bookings/cancellations': typeof AuthenticatedPostopBookingsCancellationsRoute
  '/_authenticated/postop-bookings/new': typeof AuthenticatedPostopBookingsNewRoute
  '/_authenticated/postop-bookings/planner': typeof AuthenticatedPostopBookingsPlannerRoute
  '/_authenticated/referrals/$id': typeof AuthenticatedReferralsIdRoute
  '/_authenticated/referrals/new': typeof AuthenticatedReferralsNewRoute
  '/_authenticated/postop-bookings/': typeof AuthenticatedPostopBookingsIndexRoute
  '/_authenticated/postop-bookings/$id/edit': typeof AuthenticatedPostopBookingsIdEditRoute
  '/api/public/bridge/audit': typeof ApiPublicBridgeAuditRoute
  '/api/public/bridge/health': typeof ApiPublicBridgeHealthRoute
  '/api/public/bridge/investigations': typeof ApiPublicBridgeInvestigationsRoute
  '/api/public/bridge/microbiology': typeof ApiPublicBridgeMicrobiologyRoute
  '/api/public/bridge/notifications': typeof ApiPublicBridgeNotificationsRoute
  '/api/public/bridge/patients': typeof ApiPublicBridgePatientsRoute
  '/api/public/bridge/referrals': typeof ApiPublicBridgeReferralsRoute
  '/api/public/bridge/sync': typeof ApiPublicBridgeSyncRoute
  '/api/public/bridge/verify-signature': typeof ApiPublicBridgeVerifySignatureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clinical-safety'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/setup'
    | '/admin'
    | '/analytics'
    | '/bed-board'
    | '/board'
    | '/inbox'
    | '/notifications'
    | '/notifications-audit'
    | '/permissions'
    | '/profile'
    | '/push-test'
    | '/board/ward-round'
    | '/inbox/$id'
    | '/postop-bookings/analytics'
    | '/postop-bookings/cancellations'
    | '/postop-bookings/new'
    | '/postop-bookings/planner'
    | '/referrals/$id'
    | '/referrals/new'
    | '/postop-bookings/'
    | '/postop-bookings/$id/edit'
    | '/api/public/bridge/audit'
    | '/api/public/bridge/health'
    | '/api/public/bridge/investigations'
    | '/api/public/bridge/microbiology'
    | '/api/public/bridge/notifications'
    | '/api/public/bridge/patients'
    | '/api/public/bridge/referrals'
    | '/api/public/bridge/sync'
    | '/api/public/bridge/verify-signature'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/clinical-safety'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/setup'
    | '/admin'
    | '/analytics'
    | '/bed-board'
    | '/board'
    | '/inbox'
    | '/notifications'
    | '/notifications-audit'
    | '/permissions'
    | '/profile'
    | '/push-test'
    | '/'
    | '/board/ward-round'
    | '/inbox/$id'
    | '/postop-bookings/analytics'
    | '/postop-bookings/cancellations'
    | '/postop-bookings/new'
    | '/postop-bookings/planner'
    | '/referrals/$id'
    | '/referrals/new'
    | '/postop-bookings'
    | '/postop-bookings/$id/edit'
    | '/api/public/bridge/audit'
    | '/api/public/bridge/health'
    | '/api/public/bridge/investigations'
    | '/api/public/bridge/microbiology'
    | '/api/public/bridge/notifications'
    | '/api/public/bridge/patients'
    | '/api/public/bridge/referrals'
    | '/api/public/bridge/sync'
    | '/api/public/bridge/verify-signature'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/clinical-safety'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/setup'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/bed-board'
    | '/_authenticated/board'
    | '/_authenticated/inbox'
    | '/_authenticated/notifications'
    | '/_authenticated/notifications-audit'
    | '/_authenticated/permissions'
    | '/_authenticated/profile'
    | '/_authenticated/push-test'
    | '/_authenticated/'
    | '/_authenticated/board/ward-round'
    | '/_authenticated/inbox/$id'
    | '/_authenticated/postop-bookings/analytics'
    | '/_authenticated/postop-bookings/cancellations'
    | '/_authenticated/postop-bookings/new'
    | '/_authenticated/postop-bookings/planner'
    | '/_authenticated/referrals/$id'
    | '/_authenticated/referrals/new'
    | '/_authenticated/postop-bookings/'
    | '/_authenticated/postop-bookings/$id/edit'
    | '/api/public/bridge/audit'
    | '/api/public/bridge/health'
    | '/api/public/bridge/investigations'
    | '/api/public/bridge/microbiology'
    | '/api/public/bridge/notifications'
    | '/api/public/bridge/patients'
    | '/api/public/bridge/referrals'
    | '/api/public/bridge/sync'
    | '/api/public/bridge/verify-signature'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClinicalSafetyRoute: typeof ClinicalSafetyRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SetupRoute: typeof SetupRoute
  ApiPublicBridgeAuditRoute: typeof ApiPublicBridgeAuditRoute
  ApiPublicBridgeHealthRoute: typeof ApiPublicBridgeHealthRoute
  ApiPublicBridgeInvestigationsRoute: typeof ApiPublicBridgeInvestigationsRoute
  ApiPublicBridgeMicrobiologyRoute: typeof ApiPublicBridgeMicrobiologyRoute
  ApiPublicBridgeNotificationsRoute: typeof ApiPublicBridgeNotificationsRoute
  ApiPublicBridgePatientsRoute: typeof ApiPublicBridgePatientsRoute
  ApiPublicBridgeReferralsRoute: typeof ApiPublicBridgeReferralsRoute
  ApiPublicBridgeSyncRoute: typeof ApiPublicBridgeSyncRoute
  ApiPublicBridgeVerifySignatureRoute: typeof ApiPublicBridgeVerifySignatureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-safety': {
      id: '/clinical-safety'
      path: '/clinical-safety'
      fullPath: '/clinical-safety'
      preLoaderRoute: typeof ClinicalSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/push-test': {
      id: '/_authenticated/push-test'
      path: '/push-test'
      fullPath: '/push-test'
      preLoaderRoute: typeof AuthenticatedPushTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications-audit': {
      id: '/_authenticated/notifications-audit'
      path: '/notifications-audit'
      fullPath: '/notifications-audit'
      preLoaderRoute: typeof AuthenticatedNotificationsAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/board': {
      id: '/_authenticated/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthenticatedBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bed-board': {
      id: '/_authenticated/bed-board'
      path: '/bed-board'
      fullPath: '/bed-board'
      preLoaderRoute: typeof AuthenticatedBedBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/postop-bookings/': {
      id: '/_authenticated/postop-bookings/'
      path: '/postop-bookings'
      fullPath: '/postop-bookings/'
      preLoaderRoute: typeof AuthenticatedPostopBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals/new': {
      id: '/_authenticated/referrals/new'
      path: '/referrals/new'
      fullPath: '/referrals/new'
      preLoaderRoute: typeof AuthenticatedReferralsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals/$id': {
      id: '/_authenticated/referrals/$id'
      path: '/referrals/$id'
      fullPath: '/referrals/$id'
      preLoaderRoute: typeof AuthenticatedReferralsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/postop-bookings/planner': {
      id: '/_authenticated/postop-bookings/planner'
      path: '/postop-bookings/planner'
      fullPath: '/postop-bookings/planner'
      preLoaderRoute: typeof AuthenticatedPostopBookingsPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/postop-bookings/new': {
      id: '/_authenticated/postop-bookings/new'
      path: '/postop-bookings/new'
      fullPath: '/postop-bookings/new'
      preLoaderRoute: typeof AuthenticatedPostopBookingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/postop-bookings/cancellations': {
      id: '/_authenticated/postop-bookings/cancellations'
      path: '/postop-bookings/cancellations'
      fullPath: '/postop-bookings/cancellations'
      preLoaderRoute: typeof AuthenticatedPostopBookingsCancellationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/postop-bookings/analytics': {
      id: '/_authenticated/postop-bookings/analytics'
      path: '/postop-bookings/analytics'
      fullPath: '/postop-bookings/analytics'
      preLoaderRoute: typeof AuthenticatedPostopBookingsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/$id': {
      id: '/_authenticated/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AuthenticatedInboxIdRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/_authenticated/board/ward-round': {
      id: '/_authenticated/board/ward-round'
      path: '/ward-round'
      fullPath: '/board/ward-round'
      preLoaderRoute: typeof AuthenticatedBoardWardRoundRouteImport
      parentRoute: typeof AuthenticatedBoardRoute
    }
    '/api/public/bridge/verify-signature': {
      id: '/api/public/bridge/verify-signature'
      path: '/api/public/bridge/verify-signature'
      fullPath: '/api/public/bridge/verify-signature'
      preLoaderRoute: typeof ApiPublicBridgeVerifySignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/sync': {
      id: '/api/public/bridge/sync'
      path: '/api/public/bridge/sync'
      fullPath: '/api/public/bridge/sync'
      preLoaderRoute: typeof ApiPublicBridgeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/referrals': {
      id: '/api/public/bridge/referrals'
      path: '/api/public/bridge/referrals'
      fullPath: '/api/public/bridge/referrals'
      preLoaderRoute: typeof ApiPublicBridgeReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/patients': {
      id: '/api/public/bridge/patients'
      path: '/api/public/bridge/patients'
      fullPath: '/api/public/bridge/patients'
      preLoaderRoute: typeof ApiPublicBridgePatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/notifications': {
      id: '/api/public/bridge/notifications'
      path: '/api/public/bridge/notifications'
      fullPath: '/api/public/bridge/notifications'
      preLoaderRoute: typeof ApiPublicBridgeNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/microbiology': {
      id: '/api/public/bridge/microbiology'
      path: '/api/public/bridge/microbiology'
      fullPath: '/api/public/bridge/microbiology'
      preLoaderRoute: typeof ApiPublicBridgeMicrobiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/investigations': {
      id: '/api/public/bridge/investigations'
      path: '/api/public/bridge/investigations'
      fullPath: '/api/public/bridge/investigations'
      preLoaderRoute: typeof ApiPublicBridgeInvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/health': {
      id: '/api/public/bridge/health'
      path: '/api/public/bridge/health'
      fullPath: '/api/public/bridge/health'
      preLoaderRoute: typeof ApiPublicBridgeHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/audit': {
      id: '/api/public/bridge/audit'
      path: '/api/public/bridge/audit'
      fullPath: '/api/public/bridge/audit'
      preLoaderRoute: typeof ApiPublicBridgeAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/postop-bookings/$id/edit': {
      id: '/_authenticated/postop-bookings/$id/edit'
      path: '/postop-bookings/$id/edit'
      fullPath: '/postop-bookings/$id/edit'
      preLoaderRoute: typeof AuthenticatedPostopBookingsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedBoardRouteChildren {
  AuthenticatedBoardWardRoundRoute: typeof AuthenticatedBoardWardRoundRoute
}

const AuthenticatedBoardRouteChildren: AuthenticatedBoardRouteChildren = {
  AuthenticatedBoardWardRoundRoute: AuthenticatedBoardWardRoundRoute,
}

const AuthenticatedBoardRouteWithChildren =
  AuthenticatedBoardRoute._addFileChildren(AuthenticatedBoardRouteChildren)

interface AuthenticatedInboxRouteChildren {
  AuthenticatedInboxIdRoute: typeof AuthenticatedInboxIdRoute
}

const AuthenticatedInboxRouteChildren: AuthenticatedInboxRouteChildren = {
  AuthenticatedInboxIdRoute: AuthenticatedInboxIdRoute,
}

const AuthenticatedInboxRouteWithChildren =
  AuthenticatedInboxRoute._addFileChildren(AuthenticatedInboxRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBedBoardRoute: typeof AuthenticatedBedBoardRoute
  AuthenticatedBoardRoute: typeof AuthenticatedBoardRouteWithChildren
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedNotificationsAuditRoute: typeof AuthenticatedNotificationsAuditRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPushTestRoute: typeof AuthenticatedPushTestRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPostopBookingsAnalyticsRoute: typeof AuthenticatedPostopBookingsAnalyticsRoute
  AuthenticatedPostopBookingsCancellationsRoute: typeof AuthenticatedPostopBookingsCancellationsRoute
  AuthenticatedPostopBookingsNewRoute: typeof AuthenticatedPostopBookingsNewRoute
  AuthenticatedPostopBookingsPlannerRoute: typeof AuthenticatedPostopBookingsPlannerRoute
  AuthenticatedReferralsIdRoute: typeof AuthenticatedReferralsIdRoute
  AuthenticatedReferralsNewRoute: typeof AuthenticatedReferralsNewRoute
  AuthenticatedPostopBookingsIndexRoute: typeof AuthenticatedPostopBookingsIndexRoute
  AuthenticatedPostopBookingsIdEditRoute: typeof AuthenticatedPostopBookingsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBedBoardRoute: AuthenticatedBedBoardRoute,
  AuthenticatedBoardRoute: AuthenticatedBoardRouteWithChildren,
  AuthenticatedInboxRoute: AuthenticatedInboxRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedNotificationsAuditRoute: AuthenticatedNotificationsAuditRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPushTestRoute: AuthenticatedPushTestRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPostopBookingsAnalyticsRoute:
    AuthenticatedPostopBookingsAnalyticsRoute,
  AuthenticatedPostopBookingsCancellationsRoute:
    AuthenticatedPostopBookingsCancellationsRoute,
  AuthenticatedPostopBookingsNewRoute: AuthenticatedPostopBookingsNewRoute,
  AuthenticatedPostopBookingsPlannerRoute:
    AuthenticatedPostopBookingsPlannerRoute,
  AuthenticatedReferralsIdRoute: AuthenticatedReferralsIdRoute,
  AuthenticatedReferralsNewRoute: AuthenticatedReferralsNewRoute,
  AuthenticatedPostopBookingsIndexRoute: AuthenticatedPostopBookingsIndexRoute,
  AuthenticatedPostopBookingsIdEditRoute:
    AuthenticatedPostopBookingsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClinicalSafetyRoute: ClinicalSafetyRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SetupRoute: SetupRoute,
  ApiPublicBridgeAuditRoute: ApiPublicBridgeAuditRoute,
  ApiPublicBridgeHealthRoute: ApiPublicBridgeHealthRoute,
  ApiPublicBridgeInvestigationsRoute: ApiPublicBridgeInvestigationsRoute,
  ApiPublicBridgeMicrobiologyRoute: ApiPublicBridgeMicrobiologyRoute,
  ApiPublicBridgeNotificationsRoute: ApiPublicBridgeNotificationsRoute,
  ApiPublicBridgePatientsRoute: ApiPublicBridgePatientsRoute,
  ApiPublicBridgeReferralsRoute: ApiPublicBridgeReferralsRoute,
  ApiPublicBridgeSyncRoute: ApiPublicBridgeSyncRoute,
  ApiPublicBridgeVerifySignatureRoute: ApiPublicBridgeVerifySignatureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
