
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS notify_capacity BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notify_capacity_l3 BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notify_capacity_l2 BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notify_capacity_l1 BOOLEAN NOT NULL DEFAULT TRUE;
